sudo: required
services:
  - docker

before_install:
  - docker build -t vadimdrozdenko/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vadimdrozdenko/docker-react npm run test 

